version: "3"

services: 
  postgres:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-jokedb}
      PGDATA: /data/postgres 
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: